manifest:
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: umetaro
      url-base: https://github.com/0UmetaroU0

  projects:
    - name: zmk-module-runtime-input-processor
      remote: cormoran
      revision: zmk-v0.3.0.0

    - name: zmk-feature-custom-settings
      remote: umetaro
      revision: v0.3-port

    - name: zmk
      remote: cormoran
      revision: v0.3+custom-studio-protocol
      import:
        file: app/west.yml

  self:
    path: config
